# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Example add-on my version
version: "1.2.0"
slug: example_myversion
description: Example add-on
url: "https://github.com/Skeletitor/MyFirstTest"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/skeletitor/{arch}-addon-example"
