# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:latest"
  amd64: "ghcr.io/home-assistant/amd64-base-python:latest"
  armhf: "ghcr.io/home-assistant/armhf-base-python:latest"
  armv7: "ghcr.io/home-assistant/armv7-base-python:latest"
  i386: "ghcr.io/home-assistant/i386-base-python:latest"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Expose Fenecon Home to Hassio"
  org.opencontainers.image.description: "Connect Fenecon Home Websocket and publish entities and data to Hassios integrated mqtt broker."
  org.opencontainers.image.source: "https://github.com/home-assistant/addons-example"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
#codenotary:
#  signer: tobias.roehmer@outlook.de
#  base_image: notary@home-assistant.io
