# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Fenecon2Mqtt
version: "0.1.6"
slug: fenecon2mqtt
description: Provides data from Fenecon Home Websocket as Hassio device and entities
url: "https://github.com/Skeletitor/hassio_addons/tree/main/fenecon2mqtt"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
discovery:
  - mqtt
options:
  #message: "Hello world..."
  #option1: "Text12"
  hassio:
    mqtt_broker_host: "<<IP or DNS Name of MQTT broker>>"
    mqtt_broker_port: 1883
    mqtt_broker_user: "<<mqtt Username>>"
    mqtt_broker_passwd: "<<mqtt Password>>"
    mqtt_broker_keepalive: 60
    mqtt_broker_hassio_discovery_queue: "homeassistant/sensor/fenecon"
    mqtt_broker_hassio_queue: "fenecon"
    sensor_overwrite:
      - "channel;device_class;state_class;device_unit;value_template"
      - "battery0/Tower0PackVoltage;voltage;measurement;V;{{value}}"
    sensor_uid_prefix: "fems-"
  fenecon:
    #uri: "ws://<<IP of Fenecon Home>>:8085/websocket"
    fems_ip: "<<IP or DNS Name of Fenecon Home/FEMS>>"
    fems_password: "<<Password of guest user>>"
    fems_request_channels:
      - "_sum/State"
      - "_sum/EssSoc"
      - "_sum/EssActivePower"
      - "_sum/State"
      - "_sum/EssSoc"
      - "_sum/EssActivePower"
      - "_sum/EssActivePowerL1"
      - "_sum/EssActivePowerL2"
      - "_sum/EssActivePowerL3"
      - "_sum/EssMaxApparentPower"
      - "_sum/GridMode"
      - "_sum/GridMinActivePower"
      - "_sum/GridMaxActivePower"
      - "_sum/GridActivePower"
      - "_sum/GridActivePowerL1"
      - "_sum/GridActivePowerL2"
      - "_sum/GridActivePowerL3"
      - "_sum/ProductionActivePower"
      - "_sum/ProductionDcActualPower"
      - "_sum/ProductionAcActivePower"
      - "_sum/ProductionMaxActivePower"
      - "_sum/ConsumptionActivePower"
      - "_sum/ConsumptionActivePowerL1"
      - "_sum/ConsumptionActivePowerL2"
      - "_sum/ConsumptionActivePowerL3"
      - "_sum/ConsumptionMaxActivePower"
      - "ctrlPrepareBatteryExtension0/CtrlIsBlockingEss"
      - "ctrlPrepareBatteryExtension0/CtrlIsChargingEss"
      - "ctrlPrepareBatteryExtension0/CtrlIsDischargingEss"
      - "ctrlPrepareBatteryExtension0/_PropertyIsRunning"
      - "charger0/ActualPower"
      - "charger1/ActualPower"
      - "ctrlGridOptimizedCharge0/DelayChargeState"
      - "ctrlGridOptimizedCharge0/SellToGridLimitState"
      - "ctrlGridOptimizedCharge0/DelayChargeMaximumChargeLimit"
      - "ctrlGridOptimizedCharge0/SellToGridLimitMinimumChargeLimit"
      - "ctrlGridOptimizedCharge0/_PropertyMode"
      - "ess0/Soc"
      - "ess0/Capacity"
      - "ess0/DcDischargePower"
      - "charger0/ActualPower"
      - "charger1/ActualPower"
      - "_sum/ProductionActiveEnergy"
      - "_sum/GridBuyActiveEnergy"
      - "_sum/GridSellActiveEnergy"
      - "_sum/EssDcDischargeEnergy"
      - "_sum/EssDcChargeEnergy"
      - "battery0/Tower0PackVoltage"
  log_level: INFO
schema:
  hassio:
    mqtt_broker_host: "str"
    mqtt_broker_port: "int(1024,65535)"
    mqtt_broker_user: "str"
    mqtt_broker_passwd: "str"
    mqtt_broker_keepalive: "int"
    mqtt_broker_hassio_discovery_queue: "str"
    mqtt_broker_hassio_queue: "str"
    sensor_overwrite:
      - "str?"
    sensor_uid_prefix: "str"
  fenecon:
    fems_ip: "str"
    fems_password: "str"
    fems_request_channels:
      - "str"
  log_level: list(CRITICAL|ERROR|WARNING|INFO|DEBUG|NOTSET)
image: "ghcr.io/skeletitor/{arch}-addon-fenecon2mqtt"
