# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Fenecon2Mqtt
version: "0.2.17"
slug: fenecon2mqtt
description: Provides data from Fenecon Home Websocket as a Homeassistant device and HA entities. Fenecons channels are configurable.
url: "https://github.com/Skeletitor/ha_addon_fenecon2mqtt"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
discovery:
  - mqtt
options:
  hassio:
    mqtt_broker_host: null
    mqtt_broker_port: 1883
    mqtt_broker_user: null
    mqtt_broker_passwd: null
    mqtt_broker_keepalive: 60
    mqtt_broker_hassio_discovery_queue: "homeassistant/sensor/fenecon"
    mqtt_broker_hassio_queue: "fenecon"
    sensor_overwrite:
      - "channel;device_class;state_class;device_unit;value_template;name "
    sensor_uid_prefix: "fems-"
    sensor_name_prefix: "FEMS: "
  fenecon:
    #uri: "ws://<<IP of Fenecon Home>>:8085/websocket"
    fems_ip: null
    fems_password: null
    fems_request_channels:
      - _sum/ConsumptionActiveEnergy
      - _sum/ConsumptionActivePower
      - _sum/ConsumptionActivePowerL1
      - _sum/ConsumptionActivePowerL2
      - _sum/ConsumptionActivePowerL3
      - _sum/ConsumptionMaxActivePower
      - _sum/EssActivePower
      - _sum/EssActivePowerL1
      - _sum/EssActivePowerL2
      - _sum/EssActivePowerL3
      - _sum/EssDcChargeEnergy
      - _sum/EssDcDischargeEnergy
      - _sum/EssSoc
      - _sum/GridActivePower
      - _sum/GridActivePowerL1
      - _sum/GridActivePowerL2
      - _sum/GridActivePowerL3
      - _sum/GridBuyActiveEnergy
      - _sum/GridMaxActivePower
      - _sum/GridMinActivePower
      - _sum/GridMode
      - _sum/GridSellActiveEnergy
      - _sum/ProductionActiveEnergy
      - _sum/ProductionActivePower
      - _sum/ProductionDcActualPower
      - _sum/ProductionMaxActivePower
      - _sum/State
      - battery0/Soh
      - battery0/Tower0NoOfCycles
      - battery0/Tower0PackVoltage
      - batteryInverter0/AirTemperature
      - batteryInverter0/ArmFmVersion
      - batteryInverter0/BmsPackTemperature
      - batteryInverter0/DspFmVersionMaster
      - batteryInverter0/DspFmVersionSlave
      - batteryInverter0/RadiatorTemperature
      - charger0/ActualPower
      - charger0/ActualPower
      - charger0/Current
      - charger0/State
      - charger0/Voltage
      - charger1/ActualPower
      - charger1/ActualPower
      - charger1/Current
      - charger1/State
      - charger1/Voltage
      - charger1/Voltage
      - ess0/Capacity
      - ess0/DcDischargePower
  log_level: INFO
schema:
  hassio:
    mqtt_broker_host: "str"
    mqtt_broker_port: "int(1024,65535)"
    mqtt_broker_user: "str"
    mqtt_broker_passwd: "str"
    mqtt_broker_keepalive: "int"
    mqtt_broker_hassio_discovery_queue: "str"
    mqtt_broker_hassio_queue: "str"
    sensor_overwrite:
      - "str?"
    sensor_uid_prefix: "str"
    sensor_name_prefix: "str?"
  fenecon:
    fems_ip: "str"
    fems_password: "str"
    fems_request_channels:
      - "str"
  log_level: list(CRITICAL|ERROR|WARNING|INFO|DEBUG|NOTSET)
## comment the next line for local development
image: "ghcr.io/skeletitor/{arch}-addon-fenecon2mqtt"
